### PR TITLE
translate README into Simplified Chinese

### PR DESCRIPTION
**Pull request by ArchimboldiMao**
1. Create a folder (/simplified-chinese) to store Simplified Chinese files.
2. Translate README.md into Simplified Chinese and save it to /simplified-chinese/README-cn.md.

### CODE REVIEW

**Comment by leandromoreira** [comment]
Thank you very much! Your work is much appreciated!

**Comment by ArchimboldiMao** [comment]
Thank you for creating this project. 
It gave me a lot of help. I am happy to translate into my native language. I hope that more and more people like me will see this project.

**Comment by leandromoreira** [comment]
I'll introduce the DRM section later this week as well as a `changelog section` so we can log changes to make it easier for translators.

**Comment by ArchimboldiMao** [comment]
It’s great. I will translate into Simplified Chinese too.

**Pull request merged**
