### PR TITLE
🇷🇺 Russian translation

### PR DESCRIPTION
**Pull request by notbogdan**
Hi, this took a little time but I finally managed to squeeze it out. Russian translation inbound!

### CODE REVIEW

**Comment by leandromoreira** [comment]
Thanks @notbogdan I'm gonna wait some else that knows Russian language to review.

**Comment by leandromoreira** [comment]
please help! 🦸‍♀️

**Comment by notbogdan** [comment]
Someone "productionized" the translation [here](https://github.com/leandromoreira/digital_video_introduction/issues/95#issuecomment-754286366), this is a much better version which I will try and merge into this branch at some point. This one should be good to merge ^^

**Review by leandromoreira — APPROVED** [review]

**Comment by notbogdan** [comment]
Oh sorry, I think you may have misunderstood - I meant that the translation I linked would've been good to merge, not as it is in its current form. No worries, I will open another PR.

**Comment by leandromoreira** [comment]
sorry @notbogdan =(

**Pull request merged**
