### PR TITLE
Proofread a Japanese translation

### PR DESCRIPTION
**Pull request by c-bata**
First, thanks for creating this awesome repository @leandromoreira. And also thanks for translating into Japanese @thmatuza! I hope more Japanese people will read this.

I proofread a Japanese translation. @thmatuza Could you review this?

### CODE REVIEW

**Comment by c-bata** [comment]
[nits] I think it's better to put this at ` translations/README-ja.md` or `japanese/README.md`. If you agreed, I'll rename and push it on this branch.

**Comment by thmatuza** [comment]
@c-bata Thank you for proofreading my translation! It looks good to me except following part.

AVC (H.264)標準は、情報が**NAL** 

If you see it on markdown preview, you may notice it doesn't emphasis NAL but "**" remains.
(I tried it on Chrome)
I had to put a space before and/or after "**" for fixing those Japanese markdown problems.

**Comment by c-bata** [comment]
Thanks for your review! I fixed it like:

**Comment by thmatuza** [comment]
[LGTM](https://www.lgtm.in/i/QUDtHgZRp)

**Comment by leandromoreira** [comment]
I liked the suggestion of using `translations/` and move all the translations and change their links in the main README.

**Pull request merged**
