### PR TITLE
Fix several issues for the translation document

### PR DESCRIPTION
**Pull request by lance-lmwang**

### CODE REVIEW

**Review by leandromoreira — APPROVED** [review]

**Comment by leandromoreira** [comment]
thanks @lance-lmwang do you mind to wait someone else to review this? unfortunately I don't any Mandarin :(  (or if nobody reviews it, I'll merge it as well)

**Comment by lance-lmwang** [comment]
> thanks @lance-lmwang do you mind to wait someone else to review this? unfortunately I don't any Mandarin :( (or if nobody reviews it, I'll merge it as well)

I'm OK to waiting for reviewing by someone else, thanks.

**Review by leandromoreira — APPROVED** [review]

**Comment by leandromoreira** [comment]
@lance-lmwang can I merge it now or do you have more contributions?

**Comment by lance-lmwang** [comment]
On Fri, Jul 02, 2021 at 09:45:50AM -0700, Leandro Moreira wrote:
> @lance-lmwang can I merge it now or do you have more contributions?

not for now, If nobody have more comments, please merge it anyway. 

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/leandromoreira/digital_video_introduction/pull/120#issuecomment-873127948

-- 
Thanks,
Limin Wang

**Pull request merged**
