### PR TITLE
translate README into Japanese

### PR DESCRIPTION
**Pull request by thmatuza**
1. Create a folder (/japanese) to store Japanese files.
2. Translate README.md into Japanese and save it to /japanese/README-ja.md.

### CODE REVIEW

**Comment by leandromoreira** [comment]
Thank you very much @thmatuza

**Comment by matteocontrini** [comment]
@leandromoreira seeing that the "readme" is already translated in two languages, I think I'm available to create an Italian version as well. Would that be ok? :)

**Comment by thmatuza** [comment]
@leandromoreira Thank you for creating this awesome project! It really helped me to dig into digital video. I hope more Japanese will have same experience as me!

**Comment by leandromoreira** [comment]
@thmatuza thank you too for bringing this for the Japanese people. (Japan is the place I dream to visit from a long time aog, maybe the next olympic games I pay a visit there)

**Pull request merged**
